version: '3.4'

services:
  rabbitmq:
     image: rabbitmq:3-management-alpine

  apigateway:
    image: ${DOCKER_REGISTRY-}apigateway
    build:
      context: .
      dockerfile: APIGateway/Dockerfile

  pedido:
    image: ${DOCKER_REGISTRY-}pedido
    build:
      context: .
      dockerfile: Pedido.API/Dockerfile

  catalogo:
    image: ${DOCKER_REGISTRY-}catalogo
    build:
      context: .
      dockerfile: Catalogo.API/Dockerfile

      