version: '3.4'

services:
  apigateway:
    image: ${DOCKER_REGISTRY-}apigateway
    build:
      context: .
      dockerfile: APIGateway/Dockerfile

  pedido:
    image: pedido
    build:
      context: .
      dockerfile: Pedido.API/Dockerfile

  catalogo:
    image: catalogo
    build:
      context: .
      dockerfile: Catalogo.API/Dockerfile